defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

arch:
    fully_connected:
        adaptive_activations: true
#        activation_fn: "stan"
optimizer:
  lr: 1e-2
scheduler:
  decay_rate: 0.95
  decay_steps: 3000

training:
  rec_results_freq : 1000
  rec_constraint_freq: 1000
  max_steps : 5000
  #grad_agg_freq: 2

batch_size:
  initial_condition: 150
  lowres_interior: 50 #4000
  highres_interior: 200
  no_slip: 50
  inlet: 50
  outlet: 50
  interface_left: 5 #3400
  interface_right: 50 #3400
  integral_continuity: 10