defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

arch:
    fully_connected:
        adaptive_activations: true

scheduler:
  decay_rate: 0.95
  decay_steps: 3000

training:
  rec_results_freq : 5000
  rec_constraint_freq: 5000
  max_steps : 5000

batch_size:
  initial_condition: 1000
  lowres_interior: 400 #4000
  highres_interior: 5000
  #symmetry: 8000
<<<<<<< HEAD
  no_slip: 1000
  inlet: 400
  #interface: 3400
=======
  no_slip: 100 #1200
  inlet: 400
  interface: 340 #3400
>>>>>>> 5d544bbdda42f495e0083830932333577a499553
