defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

arch:
    fully_connected:
        adaptive_activations: true
        #activation_fn: "stan"

scheduler:
  decay_rate: 0.95
  decay_steps: 3000

training:
  rec_results_freq : 1000
  rec_constraint_freq: 1000
  max_steps : 3000
  grad_agg_freq: 2

batch_size:
  initial_condition: 6000
  lowres_interior: 2000 #4000
  highres_interior: 4000
  #highres_interior1: 300
  no_slip: 2000
  inlet: 2000
  outlet: 2000
  #interface_left: 50 #3400
  #interface_right: 500 #3400
  interface: 20000
  integral_continuity: 1000