defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

arch:
    fully_connected:
        adaptive_activations: true

scheduler:
  decay_rate: 0.95
  decay_steps: 3000

training:
  rec_results_freq : 5000
  rec_constraint_freq: 5000
  max_steps : 5000

batch_size:
  initial_condition: 5000
  lowres_interior: 500 #4000
  highres_interior: 5000
  no_slip: 1000
  inlet: 500
  outlet: 1000
  interface: 1000 #3400
