defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

arch:
    fully_connected:
        adaptive_activations: true
optimizer:
  lr: 1e-4
  
scheduler:
  decay_rate: 0.5
  decay_steps: 5000

training:
  rec_results_freq : 5000
  rec_constraint_freq: 5000
  max_steps : 25000
  #grad_agg_freq: 2

batch_size:
  initial_condition: 200
  lowres_interior: 55 #4000
  highres_interior: 160
  no_slip: 1
  inlet: 1
  outlet: 1
  interface: 15 #3400
  interface_left: 1
  interface_right: 3
  integral_continuity: 10
