defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

arch:
    fully_connected:
        adaptive_activations: true
        activation_fn: "stan"

scheduler:
  decay_rate: 0.95
  decay_steps: 3000

training:
  rec_results_freq : 1000
  rec_constraint_freq: 1000
  max_steps : 3000
  grad_agg_freq: 2

batch_size:
  initial_condition: 1500
  lowres_interior: 500 #4000
  highres_interior: 1000
  #highres_interior1: 300
  no_slip: 500
  inlet: 500
  outlet: 500
  #interface_left: 50 #3400
  #interface_right: 500 #3400
  interface: 1500
  integral_continuity: 100