defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

scheduler:
  decay_rate: 0.95
  decay_steps: 3000

training:
  rec_results_freq : 5000
  rec_constraint_freq: 5000
  max_steps : 10000

batch_size:
  initial_condition: 4000
  lowres_interior: 400 #4000
  highres_interior: 10000
  symmetry: 10400
  no_slip: 1200
  #bd_pressure: 400
  interface: 3400